---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: senchart
  namespace: flux-system
spec:
  interval: 1m0s
  secretRef:
    name: senchart-auth
  url: http://chartmuseum.senapt.com:8080

