---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: audit-trail-service
  namespace: flux-system
spec:
  chart:
    spec:
      chart: audit-trail-service
      sourceRef:
        kind: HelmRepository
        name: senchart
      version: '>1.0.0'
  interval: 1m0s
  targetNamespace: default

